Add CREATE_RUN operation to port github action
port-labs/port-github-action pull request #95
Opened 2023-10-19 13:03 UTC by dvarchev

2023-10-22 16:20 UTC, talsabagport requested changes
Looks good overall! 👍  Left few comments

2023-10-22 16:20 UTC, talsabagport commented on action.yml
> +    description: 'One of the following operations: GET, UPSERT, SEARCH, BULK_UPSERT, CREATE_RUN, PATCH_RUN, DELETE'
Please add `action` to the inputs here

2023-10-22 16:20 UTC, talsabagport commented on src/operations/CreateRunOperation/CreateRunOperation.ts
> +export default class CreateActionOperation implements IOperation {
```suggestion
export default class CreateRunOperation implements IOperation {
```

2023-10-22 16:20 UTC, talsabagport commented on src/operations/OperationFactory/OperationFactory.ts
> +import CreateActionOperation from '../CreateRunOperation/CreateRunOperation';
```suggestion
import CreateRunOperation from '../CreateRunOperation/CreateRunOperation';
```

2023-10-22 16:20 UTC, talsabagport commented on src/operations/OperationFactory/OperationFactory.ts
> +				return new CreateActionOperation(input);
```suggestion
				return new CreateRunOperation(input);
```

2023-10-23 06:34 UTC, dvarchev commented on action.yml
> +    description: 'One of the following operations: GET, UPSERT, SEARCH, BULK_UPSERT, CREATE_RUN, PATCH_RUN, DELETE'
Added the action input.

2023-10-23 06:35 UTC, dvarchev commented on src/operations/CreateRunOperation/CreateRunOperation.ts
> +export default class CreateActionOperation implements IOperation {
Fixed the naming as requested

2023-10-23 06:35 UTC, dvarchev commented on src/operations/OperationFactory/OperationFactory.ts
> +				return new CreateActionOperation(input);
Fixed the naming as requested

2023-10-23 06:35 UTC, dvarchev commented on src/operations/OperationFactory/OperationFactory.ts
> +import CreateActionOperation from '../CreateRunOperation/CreateRunOperation';
Fixed the naming as requested

2023-10-23 06:37 UTC, dvarchev commented
Hey @talsabagport,
Thanks a lot for the quick review and comments. I addressed/fixed all of them. Please have a second look whenever you can.

2023-10-23 11:36 UTC, dvarchev commented
The tests fail due to missing ClientID. Looking at the workflow it appears that the secrets configuration is incorrect / missing.

2023-10-23 14:30 UTC, talsabagport commented on action.yml
> +    description: 'The port action identifier to creare run for'
```suggestion
    description: 'The port action identifier to create run for'
```

2023-10-23 14:32 UTC, talsabagport reviewed
The tests are failing because the secrets are not available to your forked repository, have you tested it at least locally?

2023-10-24 06:15 UTC, dvarchev commented
Yes, 
I have tested the PR locally. Apart from the added tests, I also tested the GA in a separate workflow using these steps:
```
      - name: Trigger test action for entity
        uses: officernd/port-github-action@main
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: CREATE_RUN
          icon: GithubActions
          blueprint: "gh-action-test-bp"
          action: "gh-action-test-entity"
          identifier: "gh-action-test-bp-entity"
          properties: |-
            {
              "text": "test", 
              "number": 1, 
              "boolean": true
            }
      - name: Trigger test create action
        uses: officernd/port-github-action@main
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: CREATE_RUN
          icon: GithubActions
          blueprint: "gh-action-test-bp"
          action: "gh-action-test"
          properties: |-
            {
              "text": "test", 
              "number": 1, 
              "boolean": true
            }
```

Unfortunately not all automated tests pass when executed on my side. Some of those tests rely on specific runIds (like `runId: 'r_1HDz2pBPYltPcfA1`) that I cannot setup on my port account so that they pass with my test clientID.

2023-10-25 08:50 UTC, talsabagport approved these changes

2023-10-25 08:50 UTC, merged